version: '3.8'

services:
  backend:
    container_name: language-school-backend
    build:
      context: .
      dockerfile: language-school-back/Dockerfile
    environment:
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_BUCKET: ${MINIO_BUCKET}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: ${DB_URL}
      SERVER_PORT: ${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - language-school-network

  frontend:
     expose:
       - "4200"
     container_name: language-school-frontend
     build:
       context: .
       dockerfile: language-school-app/Dockerfile
     depends_on:
       backend:
         condition: service_started
     networks:
       - language-school-network


  postgres:
    image: postgres:latest
    container_name: postgres_language
    environment:
      POSTGRES_USER: c417110f943e48c5a62d45633bdf9ea2
      POSTGRES_PASSWORD: 80ca53193cc6401fba4a426f75432d86
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "7896:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
      - ./init-scripts:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    restart: unless-stopped
    networks:
      - language-school-network

  minio:
    image: minio/minio:latest
    container_name: language-school-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - language-school-network

  nginx-proxy:
    image: nginx:latest
    container_name: language-school-nginx-proxy
    ports:
      - "80:80"    # HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/var/log/nginx
    networks:
      - language-school-network
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: [ "nginx", "-g", "daemon off;" ]
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  minio_data:
    driver: local
  pgdata:
    driver: local

networks:
  language-school-network:
    driver: bridge