spring.application.name=language-school-back
spring.config.import=classpath:/env.properties
server.port=${SERVER_PORT}
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.format_sql=true
spring.main.allow-bean-definition-overriding=true
minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
minio.access-key=${MINIO_ACCESS_KEY:minioadmin}
minio.bucket=${MINIO_BUCKET:language-school-files}
minio.secret-key=${MINIO_SECRET_KEY:minioadmin123}
spring.main.allow-circular-references=true
logging.level.org.springframework.security=TRACE
