spring.application.name=language-school-back
spring.config.import=classpath:/env.properties
server.port=${SERVER_PORT}
spring.datasource.url=${DB_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.properties.hibernate.format_sql=true


minio:
  endpoint: ${MINIO_ENDPOINT}
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: ${MINIO_BUCKET}