/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AssessmentItemDTO { 
    criterionId?: string;
    title?: string;
    description?: string;
    maxPoints?: number;
    sectionName?: string;
    orderIndex?: number;
    active?: boolean;
    points?: number;
    comment?: string;
    teacherPoints?: number;
    selfPoints?: number;
    teacherComment?: string;
    selfComment?: string;
}

