/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssessmentItemDTO } from './assessmentItemDTO';


export interface AssessmentDTO { 
    id?: string;
    taskId?: string;
    participationId?: string;
    assessorId?: string;
    type?: AssessmentDTO.TypeEnum;
    status?: AssessmentDTO.StatusEnum;
    totalPoints?: number;
    totalMaxPoints?: number;
    updatedAt?: string;
    items?: Array<AssessmentItemDTO>;
}
export namespace AssessmentDTO {
    export type TypeEnum = 'TEACHER' | 'SELF' | 'PEER';
    export const TypeEnum = {
        Teacher: 'TEACHER' as TypeEnum,
        Self: 'SELF' as TypeEnum,
        Peer: 'PEER' as TypeEnum
    };
    export type StatusEnum = 'DRAFT' | 'SUBMITTED';
    export const StatusEnum = {
        Draft: 'DRAFT' as StatusEnum,
        Submitted: 'SUBMITTED' as StatusEnum
    };
}


