/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssessmentDTO } from './assessmentDTO';
import { AssessmentItemDTO } from './assessmentItemDTO';


export interface ParticipationAssessmentDTO { 
    taskId?: string;
    participationId?: string;
    totalMaxPoints?: number;
    teacherTotal?: number;
    selfTotal?: number;
    criteria?: Array<AssessmentItemDTO>;
    teacherAssessment?: AssessmentDTO;
    selfAssessment?: AssessmentDTO;
}

