/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PeerReviewAssignmentDTO { 
    id?: string;
    taskId?: string;
    reviewerTeamId?: string;
    reviewedTeamId?: string;
    targetParticipationId?: string;
    assessmentId?: string;
    status?: PeerReviewAssignmentDTO.StatusEnum;
    createdAt?: string;
    submittedAt?: string;
    teacherEditorId?: string;
    teacherEditedAt?: string;
}
export namespace PeerReviewAssignmentDTO {
    export type StatusEnum = 'ASSIGNED' | 'WITHOUT_REVIEWER' | 'SUBMITTED' | 'TEACHER_REVIEW_REQUIRED' | 'TEACHER_EDITED' | 'FINAL';
    export const StatusEnum = {
        Assigned: 'ASSIGNED' as StatusEnum,
        WithoutReviewer: 'WITHOUT_REVIEWER' as StatusEnum,
        Submitted: 'SUBMITTED' as StatusEnum,
        TeacherReviewRequired: 'TEACHER_REVIEW_REQUIRED' as StatusEnum,
        TeacherEdited: 'TEACHER_EDITED' as StatusEnum,
        Final: 'FINAL' as StatusEnum
    };
}


