/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PeerReviewResultDTO } from './peerReviewResultDTO';


export interface PeerReviewResultsDTO { 
    taskId?: string;
    peerReviewEnabled?: boolean;
    peerReviewDistributionType?: PeerReviewResultsDTO.PeerReviewDistributionTypeEnum;
    peerReviewerVisibleToTeams?: boolean;
    peerReviewConfirmedAt?: string;
    totalMaxPoints?: number;
    results?: Array<PeerReviewResultDTO>;
}
export namespace PeerReviewResultsDTO {
    export type PeerReviewDistributionTypeEnum = 'MANUAL' | 'PAIR' | 'CIRCLE' | 'RANDOM_PAIR' | 'RANDOM_CIRCLE';
    export const PeerReviewDistributionTypeEnum = {
        Manual: 'MANUAL' as PeerReviewDistributionTypeEnum,
        Pair: 'PAIR' as PeerReviewDistributionTypeEnum,
        Circle: 'CIRCLE' as PeerReviewDistributionTypeEnum,
        RandomPair: 'RANDOM_PAIR' as PeerReviewDistributionTypeEnum,
        RandomCircle: 'RANDOM_CIRCLE' as PeerReviewDistributionTypeEnum
    };
}


