/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskCriterionDTO } from './taskCriterionDTO';
import { AssessmentDTO } from './assessmentDTO';
import { PeerReviewAssignmentDTO } from './peerReviewAssignmentDTO';


export interface PeerReviewAccessDTO { 
    taskId?: string;
    assignment?: PeerReviewAssignmentDTO;
    assessment?: AssessmentDTO;
    reviewerTeamId?: string;
    reviewerTeamName?: string;
    reviewedTeamId?: string;
    reviewedTeamName?: string;
    targetParticipationId?: string;
    status?: PeerReviewAccessDTO.StatusEnum;
    canSubmit?: boolean;
    totalMaxPoints?: number;
    criteria?: Array<TaskCriterionDTO>;
}
export namespace PeerReviewAccessDTO {
    export type StatusEnum = 'ASSIGNED' | 'WITHOUT_REVIEWER' | 'SUBMITTED' | 'TEACHER_REVIEW_REQUIRED' | 'TEACHER_EDITED' | 'FINAL';
    export const StatusEnum = {
        Assigned: 'ASSIGNED' as StatusEnum,
        WithoutReviewer: 'WITHOUT_REVIEWER' as StatusEnum,
        Submitted: 'SUBMITTED' as StatusEnum,
        TeacherReviewRequired: 'TEACHER_REVIEW_REQUIRED' as StatusEnum,
        TeacherEdited: 'TEACHER_EDITED' as StatusEnum,
        Final: 'FINAL' as StatusEnum
    };
}


