/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDTO } from './userDTO';


export interface TaskStudentDTO { 
    id?: number;
    name?: string;
    description?: string;
    deadline?: string;
    taskStatus?: TaskStudentDTO.TaskStatusEnum;
    teacher?: UserDTO;
}
export namespace TaskStudentDTO {
    export type TaskStatusEnum = 'COMPLETE' | 'OVERDUE' | 'PENDING';
    export const TaskStatusEnum = {
        Complete: 'COMPLETE' as TaskStatusEnum,
        Overdue: 'OVERDUE' as TaskStatusEnum,
        Pending: 'PENDING' as TaskStatusEnum
    };
}


