/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttachmentDownloadInfo } from './attachmentDownloadInfo';


export interface TaskParticipationDTO { 
    id?: string;
    studentId?: string;
    studentName?: string;
    captain?: boolean;
    mark?: number;
    averageMark?: number;
    votesCount?: number;
    solutionStatus?: TaskParticipationDTO.SolutionStatusEnum;
    submittedAt?: string;
    selectedSolution?: boolean;
    attachments?: Array<AttachmentDownloadInfo>;
}
export namespace TaskParticipationDTO {
    export type SolutionStatusEnum = 'DRAFT' | 'SUBMITTED' | 'SELECTED' | 'LOCKED' | 'OVERDUE';
    export const SolutionStatusEnum = {
        Draft: 'DRAFT' as SolutionStatusEnum,
        Submitted: 'SUBMITTED' as SolutionStatusEnum,
        Selected: 'SELECTED' as SolutionStatusEnum,
        Locked: 'LOCKED' as SolutionStatusEnum,
        Overdue: 'OVERDUE' as SolutionStatusEnum
    };
}


