/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TaskDTO { 
    id?: string;
    name?: string;
    description?: string;
    deadline?: string;
    courseId?: string;
    courseName?: string;
    totalPoints?: number;
    maxTeamSize?: number;
    minTeamSize?: number;
    maxTeamsAmount?: number;
    minTeamsAmount?: number;
    votesThreshold?: number;
    teamsCreationTimeout?: string;
    teamType?: TaskDTO.TeamTypeEnum;
    resolveType?: TaskDTO.ResolveTypeEnum;
    submissionClosed?: boolean;
    peerReviewEnabled?: boolean;
    peerReviewDistributionType?: TaskDTO.PeerReviewDistributionTypeEnum;
    peerReviewerVisibleToTeams?: boolean;
    peerReviewConfirmedAt?: string;
}
export namespace TaskDTO {
    export type TeamTypeEnum = 'RANDOM' | 'FREEROAM' | 'DRAFT';
    export const TeamTypeEnum = {
        Random: 'RANDOM' as TeamTypeEnum,
        Freeroam: 'FREEROAM' as TeamTypeEnum,
        Draft: 'DRAFT' as TeamTypeEnum
    };
    export type ResolveTypeEnum = 'FIRST_SUBMITTED_SOLUTION' | 'LAST_SUBMITTED_SOLUTION' | 'CAPTAINS_SOLUTION' | 'MOST_VOTES_SOLUTION' | 'AT_LEAST_VOTES_SOLUTION';
    export const ResolveTypeEnum = {
        FirstSubmittedSolution: 'FIRST_SUBMITTED_SOLUTION' as ResolveTypeEnum,
        LastSubmittedSolution: 'LAST_SUBMITTED_SOLUTION' as ResolveTypeEnum,
        CaptainsSolution: 'CAPTAINS_SOLUTION' as ResolveTypeEnum,
        MostVotesSolution: 'MOST_VOTES_SOLUTION' as ResolveTypeEnum,
        AtLeastVotesSolution: 'AT_LEAST_VOTES_SOLUTION' as ResolveTypeEnum
    };
    export type PeerReviewDistributionTypeEnum = 'MANUAL' | 'PAIR' | 'CIRCLE' | 'RANDOM_PAIR' | 'RANDOM_CIRCLE';
    export const PeerReviewDistributionTypeEnum = {
        Manual: 'MANUAL' as PeerReviewDistributionTypeEnum,
        Pair: 'PAIR' as PeerReviewDistributionTypeEnum,
        Circle: 'CIRCLE' as PeerReviewDistributionTypeEnum,
        RandomPair: 'RANDOM_PAIR' as PeerReviewDistributionTypeEnum,
        RandomCircle: 'RANDOM_CIRCLE' as PeerReviewDistributionTypeEnum
    };
}


