/**
 * Language School API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupDTO } from './groupDTO';


export interface UserFullDTO { 
    id?: number;
    firstName?: string;
    lastName?: string;
    email?: string;
    groups?: Array<GroupDTO>;
    role?: UserFullDTO.RoleEnum;
}
export namespace UserFullDTO {
    export type RoleEnum = 'TEACHER' | 'STUDENT' | 'ADMIN';
    export const RoleEnum = {
        Teacher: 'TEACHER' as RoleEnum,
        Student: 'STUDENT' as RoleEnum,
        Admin: 'ADMIN' as RoleEnum
    };
}


